apiVersion: apps/v1
kind: Deployment
metadata:
  name: <your-service-name>
spec:
  replicas: 2
  selector:
    matchLabels:
      app: <your-service-name>
  template:
    metadata:
      labels:
        app: <your-service-name>
    spec:
      containers:
        - name: <your-service-name>
          image: <your-registry>/<your-service-name>:<version>
          ports:
            - containerPort: 8080

          env:
            - name: FEATURE_FLAG
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: FEATURE_FLAG
            - name: API_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: my-configmap
                  key: API_ENDPOINT

            - name: SENSITIVE_ENV
              valueFrom:
               secretKeyRef:
                 name: my-secret
                 key: sensitive-key
