# Description: This file contains the infrastructure configuration for the TeachMe project.
# It contains the configuration for the following services:
# - Kafka
# - Redis
# - Blob Storage
############################################################################################################
# Kafka
############################################################################################################
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          env:
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_SERVER_ID
              value: "1"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 2
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: confluentinc/cp-kafka:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 29092
          env:
            - name: KAFKA_LISTENERS
              value: "LISTENER_EXTERNAL://:9092,INTERNAL://:29092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "LISTENER_EXTERNAL://:9092,INTERNAL://:29092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "INTERNAL"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "INTERNAL:PLAINTEXT,LISTENER_EXTERNAL:PLAINTEXT"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - name: external
      protocol: TCP
      port: 9092
      targetPort: 9092
    - name: internal
      protocol: TCP
      port: 29092
      targetPort: 29092
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kcat
  labels:
    app: kcat
spec:
  selector:
    matchLabels:
      app: kcat
  replicas: 1
  template:
    metadata:
      labels:
        app: kcat
    spec:
      containers:
        - name: kafka-kcat
          image: confluentinc/cp-kafkacat:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh"]
          args: ["-c", "trap : TERM INT; sleep infinity & wait"]
---
############################################################################################################
# Redis Service
############################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-backend
  template:
    metadata:
      labels:
        app: redis-backend
    spec:
      containers:
        - name: redis-backend
          image: redis/redis-stack-server:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 6379
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-backend
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
############################################################################################################
# Blob Storage
############################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob-storage-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob-storage
  template:
    metadata:
      labels:
        app: blob-storage
    spec:
      containers:
        - name: blob-storage
          image: mcr.microsoft.com/azure-storage/azurite
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 10000
          envFrom:
            - configMapRef:
                name: teachme-config
---
apiVersion: v1
kind: Service
metadata:
  name: blob-storage-service
spec:
  selector:
    app: blob-storage
  ports:
    - name: main
      protocol: TCP
      port: 10000
      targetPort: 10000
    - name: queue
      protocol: TCP
      port: 10001
      targetPort: 10001
    - name: table
      protocol: TCP
      port: 10002
      targetPort: 10002
  type: ClusterIP
---

